//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadmintonWeb.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coachs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coachs()
        {
            this.RollCalls = new HashSet<RollCalls>();
            this.UserModules = new HashSet<UserModules>();
        }
    
        public int CoachID { get; set; }
        public string CoachName { get; set; }
        public string Images { get; set; }
        public int FacilityID { get; set; }
        public int TypeUserID { get; set; }
        public int GenderID { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public int StatusID { get; set; }
        public int Education { get; set; }
        public string Experience { get; set; }
        public int Level { get; set; }
        public string TaxCode { get; set; }
        public string BankName { get; set; }
        public string BankNumber { get; set; }
        public System.DateTime WorkingStart { get; set; }
        public string HealthCondition { get; set; }
        public string CCCD { get; set; }
        public string PlaceOfOrigin { get; set; }
        public string PlaceOfResidence { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public int MaritalStatus { get; set; }
        public string Description { get; set; }
        public string NamePerson { get; set; }
        public string Relationship { get; set; }
        public string PhoneNumber { get; set; }
        public string UserCreated { get; set; }
        public string UserUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual Facilitys Facilitys { get; set; }
        public virtual TypeUsers TypeUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RollCalls> RollCalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserModules> UserModules { get; set; }
    }
}
