//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadmintonWeb.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facilitys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facilitys()
        {
            this.Coachs = new HashSet<Coachs>();
        }
    
        public int FacilityID { get; set; }
        public string FacilityName { get; set; }
        public string Address { get; set; }
        public decimal Longtitude { get; set; }
        public decimal Latitude { get; set; }
        public string UserCreated { get; set; }
        public string UserUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coachs> Coachs { get; set; }
    }
}
