//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadmintonWeb.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningProcess
    {
        public int LearningProcessID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public string CoachName { get; set; }
        public string LearningOutComes { get; set; }
        public string Comment { get; set; }
        public string Feedback { get; set; }
    }
}
