//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadmintonWeb.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RollCalls
    {
        public int RollCallID { get; set; }
        public int StudentID { get; set; }
        public int CoachID { get; set; }
        public int isCheck { get; set; }
        public int StatusID { get; set; }
        public string UserCreated { get; set; }
        public string UserUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual Coachs Coachs { get; set; }
        public virtual Students Students { get; set; }
    }
}
