//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadmintonWeb.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.RollCalls = new HashSet<RollCalls>();
        }
    
        public int StudentID { get; set; }
        public int FacilityID { get; set; }
        public int CoachID { get; set; }
        public int TimeID { get; set; }
        public int TypeUserID { get; set; }
        public string StudentName { get; set; }
        public string Images { get; set; }
        public Nullable<int> GenderID { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phone { get; set; }
        public int StatusID { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public Nullable<int> Level { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Tuitions { get; set; }
        public System.DateTime StudyStart { get; set; }
        public string HealthCondition { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string GuardianName { get; set; }
        public string Relationship { get; set; }
        public string GuardianPhone { get; set; }
        public string Description { get; set; }
        public string UserCreated { get; set; }
        public string UserUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RollCalls> RollCalls { get; set; }
        public virtual Time Time { get; set; }
        public virtual TypeUsers TypeUsers { get; set; }
    }
}
