//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadmintonWeb.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModules
    {
        public decimal UserModuleID { get; set; }
        public decimal ModuleID { get; set; }
        public int CoachID { get; set; }
        public int IsView { get; set; }
        public int IsInsert { get; set; }
        public int IsDelete { get; set; }
        public int IsUpdate { get; set; }
    
        public virtual ModuleAccess ModuleAccess { get; set; }
        public virtual Coachs Coachs { get; set; }
    }
}
